name: Compile LaTeX Papers

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        paper:
          - theory
          - paper1
          - paper2
          - paper3
          - paper4

    steps:
      - uses: actions/checkout@v4

      - name: Install minimal LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            texlive-latex-recommended \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-science \
            texlive-bibtex-extra \
            biber \
            latexmk \
            lmodern \
            ghostscript \
            fonts-freefont-otf \
            fonts-lmodern

      - name: Compile all .tex files in folder
        working-directory: papers/${{ matrix.paper }}
        run: |
          mkdir -p ../../pdf/${{ matrix.paper }}
          for texfile in *.tex; do
            echo "Compiling $texfile"
            latexmk -pdf -interaction=nonstopmode -halt-on-error "$texfile"
            pdffile="${texfile%.tex}.pdf"
            if [ -f "$pdffile" ]; then
              cp "$pdffile" ../../pdf/${{ matrix.paper }}/
            fi
          done

      - name: Upload PDFs (for internal use)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.paper }}-pdfs
          path: pdf/${{ matrix.paper }}/*.pdf

  upload-to-sftp:
    name: Upload PDFs to Personal Site
    runs-on: ubuntu-latest
    needs: build  # wait until all matrix builds are done

    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: all-pdfs

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Upload PDFs to SFTP
        run: |
          sudo apt-get update && sudo apt-get install -y lftp
          lftp -u "$SFTP_USER","$SFTP_PASS" sftp://realsoft.fi <<EOF
          set sftp:connect-program "ssh -a -x -o StrictHostKeyChecking=yes"
          mirror -R ./pdf /target/folder/on/server
          bye
      EOF
        env:
          SFTP_USER: ${{ secrets.SFTP_USER }}
          SFTP_PASS: ${{ secrets.SFTP_PASS }}
