name: Compile LaTeX Papers

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        paper:
          - blackholeentropy


    steps:
    - uses: actions/checkout@v4

    - name: Install LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-full

    - name: Compile PDF
      working-directory: ${{ matrix.paper }}
      run: |
        pdflatex -interaction=nonstopmode blackholeentropy.tex
        bibtex blackholeentropy || true
        pdflatex -interaction=nonstopmode blackholeentropy.tex
        pdflatex -interaction=nonstopmode blackholeentropy.tex

    - name: Upload PDF
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.paper }}-pdf
        path: ${{ matrix.paper }}/blackholeentropy.pdf
