name: Compile LaTeX Papers

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        paper:
          - paper1

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          pip install -r simulations/${{ matrix.paper }}/requirements.txt

      - name: Install minimal LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            texlive-latex-recommended \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-science \
            texlive-bibtex-extra \
            biber \
            latexmk \
            lmodern \
            ghostscript \
            fonts-freefont-otf \
            fonts-lmodern

      - name: Run Simulation to Generate Figures
        run: |
          python simulations/${{ matrix.paper }}/schwarzchild_entropy.py \
            --output-dir source/${{ matrix.paper }}/illustrations

      - name: Compile LaTeX
        working-directory: source/${{ matrix.paper }}
        run: |
          latexmk -pdf -interaction=nonstopmode -halt-on-error blackholeentropy.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.paper }}-pdf
          path: source/${{ matrix.paper }}/blackholeentropy.pdf
